# Generated by Django 5.2.2 on 2025-06-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection (title) values ('collection1')
""", """
        DELETE FROM store_collection where title = 'collection1'
""")
    ]
